### PR TITLE
Fix emoji suggestion logic

### LINKED ISSUE #2460: No suggestions/emoji suggestions displaying
### Short description

If enabling the **Display suggestions** option and testing out the keyboard, no suggestions show up, including no emojis, and only show the word you're typing with different number suffixes appended. Emoji suggestions don't display either.

My backup file:
[backup_dev.patrickgold.florisboard.beta_94_1714046783601.zip](https://github.com/florisboard/florisboard/files/15109600/backup_dev.patrickgold.florisboard.beta_94_1714046783601.zip)

If there are any more details necessary I can provide them.

Possibly related to #2266 

### Steps to reproduce

1. Enable Display suggestions
2. Type something
3. Suggestions don't work properly

### FlorisBoard Version

0.4.0-beta02

### Install Source

F-Droid

### Device

Motorola G84

### Android

14, Rooted

### PR DESCRIPTION
**Pull request by patrickgold**
This PR should fix #2460.

@snaik20 I am requesting your review as you were the original implementer and need to know if I messed up something (like for instance the supported emoji set where I am not sure how to use that with the new logic)

### CODE REVIEW

File: app/src/main/kotlin/dev/patrickgold/florisboard/ime/media/emoji/EmojiSuggestionProvider.kt [hunk 1]
```diff
@@ -32,24 +32,53 @@ private const val EMOJI_SUGGESTION_QUERY_MIN_LENGTH = 3
...
+    }
+
+    override suspend fun preload(subtype: Subtype) {
+        subtype.locales().forEach { locale ->
+            cachedEmojiMappings.get(locale) {
+                val map = mutableMapOf<EmojiSkinTone, MutableList<Emoji>>()
+                EmojiLayoutData.get(context, locale).values.flatten().forEach { emojiSet ->
+                    emojiSet.emojis.forEach { emoji ->
+                        val list = map.getOrPut(emoji.skinTone) { mutableListOf() }
+                        list.add(emoji)
```
Comment (snaik20) [inline app/src/main/kotlin/dev/patrickgold/florisboard/ime/media/emoji/EmojiSuggestionProvider.kt:56]: Is the list supposed to be added back to the map. I haven't setup the app ever since rust changes got merged, so I am not able to run myself and verify this

File: app/src/main/kotlin/dev/patrickgold/florisboard/ime/media/emoji/EmojiSuggestionProvider.kt [hunk 2]
```diff
@@ -32,24 +32,53 @@ private const val EMOJI_SUGGESTION_QUERY_MIN_LENGTH = 3
...
+                    }
+                }
+                map.map { it.key to it.value.toList() }.toMap()
```
Comment (snaik20) [inline app/src/main/kotlin/dev/patrickgold/florisboard/ime/media/emoji/EmojiSuggestionProvider.kt:59]: Could we move this logic into `EmojiLayoutData`

File: app/src/main/kotlin/dev/patrickgold/florisboard/ime/media/emoji/EmojiSuggestionProvider.kt [hunk 3]
```diff
@@ -32,24 +32,53 @@ private const val EMOJI_SUGGESTION_QUERY_MIN_LENGTH = 3
...
     private val editorInstance by context.editorInstance()
     private val subtypeManager by context.subtypeManager()
-    private val supportedEmojiSet: Set<Emoji> by lazy { initSupportedEmojiSet() }
+    private lateinit var supportedEmojiSet: Set<Emoji>
     private val lettersRegex = "^:[A-Za-z]*$".toRegex()
 
+    private val cachedEmojiMappings = Cache.Builder().build<FlorisLocale, Map<EmojiSkinTone, List<Emoji>>>()
+
+    override suspend fun create() {
+        //supportedEmojiSet = initSupportedEmojiSet()
```
Comment (snaik20) [inline app/src/main/kotlin/dev/patrickgold/florisboard/ime/media/emoji/EmojiSuggestionProvider.kt:46]: nit: we can remove this as it is unused now

**Review by snaik20 — COMMENTED** [review]
Seems to fix the issue, just have few concerns.

File: app/src/main/kotlin/dev/patrickgold/florisboard/ime/core/Subtype.kt [hunk 4]
```diff
@@ -73,6 +73,15 @@ data class Subtype(
...
     }
 
+    /**
+     * Returns an accumulated list of all locales of this subtype.
+     */
+    fun locales(): List<FlorisLocale> {
+        val locales = mutableListOf(primaryLocale)
+        locales.addAll(secondaryLocales)
+        return locales
+    }
```
[the remark this answers is not in the document]
Comment (patrickgold) [reply app/src/main/kotlin/dev/patrickgold/florisboard/ime/core/Subtype.kt:83]: Will look into it, but I do not want to break the Subtype API as it is otherwise stable

File: app/src/main/kotlin/dev/patrickgold/florisboard/ime/media/emoji/EmojiLayoutData.kt [hunk 5]
```diff
@@ -17,131 +17,127 @@
...
+            return get(context, resolveEmojiAssetPath(context, locale))
+        }
 
-    var ec: EmojiCategory? = null
-    var emojiEditorList: MutableList<Emoji>? = null
+        private fun loadEmojiDataMap(context: Context, path: String): EmojiLayoutData {
+            val layouts = EmojiLayoutData()
+            for (category in EmojiCategory.entries) {
+                layouts[category] = mutableListOf()
+            }
```
[the remark this answers is not in the document]
Comment (patrickgold) [reply app/src/main/kotlin/dev/patrickgold/florisboard/ime/media/emoji/EmojiLayoutData.kt:50]: Not possible because Kotlin uses references and if I say `val layouts = Empty` I am modifying the Empty object. I could consider a `clone()` method though

File: app/src/main/kotlin/dev/patrickgold/florisboard/ime/media/emoji/EmojiLayoutData.kt [hunk 6]
```diff
@@ -17,131 +17,127 @@
...
+         * - {language}.txt
+         *
+         * @param context The context used to access application assets.
+         * @param locale The locale to resolve for.
+         *
+         * @return The path to the emoji asset file, or the root path ("ime/media/emoji/root.txt") if no match is found.
+         */
+        private fun resolveEmojiAssetPath(context: Context, locale: FlorisLocale): String {
+            val rootPath = "ime/media/emoji/root.txt"
+            val emojiAssets = context.assets.list("ime/media/emoji/")?.toList() ?: return rootPath
```
[the remark this answers is not in the document]
Comment (patrickgold) [reply app/src/main/kotlin/dev/patrickgold/florisboard/ime/media/emoji/EmojiLayoutData.kt:120]: Yes you are right, the nullability of list comes from Kotlin<->Java typing issues, if the path does not exist an IOException is thrown. I reworked it now so if the language has no associated file a new empty mapping is returned.

File: app/src/main/kotlin/dev/patrickgold/florisboard/ime/media/emoji/EmojiSuggestionProvider.kt (hunk 2 above)
Comment (patrickgold) [reply app/src/main/kotlin/dev/patrickgold/florisboard/ime/media/emoji/EmojiSuggestionProvider.kt:59]: I reworked the whole EMojiData stuff, see the new changes

File: app/src/main/kotlin/dev/patrickgold/florisboard/ime/media/emoji/EmojiSuggestionProvider.kt (hunk 3 above)
Comment (patrickgold) [reply app/src/main/kotlin/dev/patrickgold/florisboard/ime/media/emoji/EmojiSuggestionProvider.kt:46]: removed

File: app/src/main/kotlin/dev/patrickgold/florisboard/ime/core/Subtype.kt (hunk 4 above)
[the remark this answers is not in the document]
Comment (patrickgold) [reply app/src/main/kotlin/dev/patrickgold/florisboard/ime/core/Subtype.kt:83]: Will keep this as is for now

**Comment by patrickgold** [comment]
Above commits apply your suggestions, rework how emoji data is stored and fix letter casing issues when doing the actual suggestion search.

**Review by snaik20 — APPROVED** [review]
